services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  migrate:
    image: event-system
    command: python -m app.init_db
    depends_on:
      db:
        condition: service_healthy


  api:
    build: .
    image: event-system
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully


  worker:
    image: event-system
    command: python -m app.worker
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      migrate:
        condition: service_completed_successfully


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db