apiVersion: apps/v1
kind: Deployment
metadata:
  name: proccessment-events-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proccessment-events-system
  template:
    metadata:
      labels:
        app: proccessment-events-system
    spec:
      initContainers:
      - name: migrate
        image: proccessment-events-system:1.0
        command: ["sh","-c","alembic upgrade head"]
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres-service:5432/events_db"
      containers:
      - name: proccessment-events-system
        image: proccessment-events-system:1.0
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres-service:5432/events_db"